name: Test saidaiKoyakusu

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up permission for scripts
      run: chmod +x saidaiKoyakusu.sh test_saidaiKoyakusu.sh

    - name: Run tests
      run: ./test_saidaiKoyakusu.sh


